theme: jekyll-theme-minimal
title: Giada Franz
logo: /assets/img/avatar.jpg
description: Contact
Department of Mathematics
Massachusetts Institute of Technology
77 Massachusetts Ave
Cambridge, MA 02139
gfranz at mit dot edu
